id: IE7051C0B
default_language: pt
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:10.509130
last_modified: 2023-01-04 11:28:10.509148
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  7A7F:
    title: Biography of Patrul Rinpoche
    base_file: 7A7F.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
